---
title: "R Markdown for defining microbial dysbiosis"
date: "02/14/2025" #last update
output: 
  html_document: 
    toc: yes
    toc_float:
      collapsed: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, message=F}

library(ggplot2)
library(phyloseq)
library(randomForest)
library(tidyverse)
library(ggpubr)
library(microbiome)
library(dysbiosisR)
library(ggvenn)
library(NBZIMM)
library(ZIBR)
library(reshape)
library(RColorBrewer)


```

```{r load data}

ps_data <- readRDS("data/ps_data")


```

```{r cleanup and transformations}


#remove Caucasian subjects
ps_data  <- subset_samples(ps_data, Race_ID == "African.American")

# Extract sample data as a data frame
sample_df <- as_data_frame(sample_data(ps_data))

# Add Age_Cat2
sample_df <- sample_df %>%
  mutate(Age = as.numeric(as.character(Age))) %>%
  mutate(Age_Cat2 = case_when(
    Age < 40 ~ "Less than 40", 
    Age >= 40 & Age < 60 ~ "40 to 59", 
    Age >= 60 ~ "60+"
  ))

sample_df <- as.data.frame(sample_df)

#Preserve original rownames (sample names)
rownames(sample_df) <- rownames(ps_data@sam_data)


identical(colnames(ps_data@otu_table), rownames(sample_df))

# add back to physeq
sample_data(ps_data) <- sample_data(sample_df)

#convert phylseq object into a dataframe 
ps_data.df <- psmelt(ps_data)

#cleanup Genus names
ps_data.df$Genus <- sub("g__", "", ps_data.df$Genus)

#cleanup Phyla names
ps_data.df$Phylum <- sub("p__", "", ps_data.df$Phylum)

#transform counts to relative abundances
ps_rel <- transform_sample_counts(ps_data, function(OTU) OTU/sum(OTU))

#convert the relative abundance data into a dataframe
ps_rel.df <- psmelt(ps_rel)

#cleanup Genus names
ps_rel.df$Genus <- sub("g__", "", ps_rel.df$Genus)



```

```{r plot options}

#set the theme for all plots
theme_set(theme_bw()) 

#a color palette for use in plotting
palette <- c("lightpink", "cornflowerblue", "yellow2", "darkblue", "darkorange1", "deeppink", "darkviolet", "palegreen",  "springgreen4", "black", "goldenrod", "red", "blue", "#3DB7E9",  "#D55E00", "#F0E442",'#253494', "gray50", "purple", "orange", "lightgreen", "forestgreen") 

 
```

## Explore metadata 

```{r prep metadata file}

df.meta <- as(sample_data(ps_data), "data.frame") 


```

```{r only one observation per particpant}

df.meta.unique <- df.meta[!duplicated(df.meta$Person_ID), ]

df.meta.unique %>% count(Hair_Type)

df.meta.unique %>% count(Race_ID)

df.meta.unique %>% count(Gender)

df.meta.unique %>% count(Cleansing_Freq)

range(df.meta.unique$Age)

```

```{r how many participants}

#check the number of participants 
length(unique(df.meta$Person_ID))

#check the number of samples per participants
df.meta %>% 
  count(Person_ID) %>% 
  arrange(desc(n))

#check the number of samples per hair site type
df.meta %>% 
  count(Area_Cond)

#check the age ranges 

range(df.meta$Age)



```

```{r Co-variate associations w/ Age}

# Density
ggplot(df.meta.unique, aes(x = Age, y = Density_Scale)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_classic() +
  stat_cor() +
  labs(x = "Age (years)",
       y = "Scalp Density") +
 theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.text.x = element_text(family = "Arial", size = 12),
        axis.text.y = element_text(family = "Arial", size = 12))+
  theme_bw()


#  stress
ggplot(df.meta.unique, aes(x = Age, y = Stress_Scale)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_classic() +
  stat_cor() +
  labs(x = "Age (years)",
       y = "Scalp Stress") +
  theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.text.x = element_text(family = "Arial", size = 12),
        axis.text.y = element_text(family = "Arial", size = 12))+
  theme_bw()



```


```{r}

#check the number of samples per participants
df.meta %>% 
  count(Person_ID, X.SampleID)


```


## Explore taxonomy

```{r basic info}

#total number of sequences
sum(ps_data.df$Abundance)

```

```{r percentages of phyla}

#percentage of each phylum in descending order
percent_phyla <- ps_data.df %>% 
  group_by(Phylum) %>% 
  summarize(sum = sum(Abundance/1720130)*100) %>% 
  arrange(desc(sum))
percent_phyla 

#percentage of each genus in descending order
percent_genera <- ps_data.df %>% 
  group_by(Genus) %>% 
  summarize(sum = sum(Abundance/1720130)*100) %>% 
  arrange(desc(sum))
percent_genera



```

```{r Average relative abundance of major genera}

ps_data.df %>% 
  filter(Genus == c("Staphylococcus", "Corynebacterium", "Propionibacterium")) %>% 
  group_by(Genus, Area_Cond) %>% 
  summarize(average = sum(Abundance/1720130)*100)

ps_data.df %>% 
  filter(Genus == c("Staphylococcus", "Corynebacterium", "Propionibacterium")) %>% 
  group_by(Genus, Area_Cond) %>% 
  summarize(average = sum(Abundance/1720130)*100) %>% 
  ggplot(aes(Area_Cond, average, fill = Genus))+
  geom_bar(stat="identity")+
    coord_flip()+
    theme_bw()+
  scale_fill_viridis_d()+
  labs(x = "", y = "Average Relative Abundance (%)")


```

```{r Abundant Genera}

plot_df <- ps_rel.df %>% 
  mutate(Genus = ifelse(Abundance < 0.05, " Other < 5%", Genus),
         Genus = ifelse(is.na(Genus) | Genus == "", "Unclassified", Genus)) %>%
  group_by(Sample, Area_Cond, Genus) %>% 
  summarize(Abundance = sum(Abundance), .groups = "drop") %>%
  group_by(Area_Cond, Genus) %>%
  summarize(mean_abundance = mean(Abundance) * 100,
    sd_abundance = sd(Abundance) * 100,
    .groups = "drop")

ggplot(plot_df, aes(x = Genus, y = mean_abundance, fill = Area_Cond)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.9), alpha=0.7) +
  geom_errorbar(aes(ymin = mean_abundance - sd_abundance, ymax = mean_abundance + sd_abundance),
                width = 0.3, position = position_dodge(width = 0.9)) +
  theme_bw() +
  labs(x = "", y = "Average Relative Abundance (%)") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        legend.title = element_blank()) +
  stat_compare_means(
    method = "wilcox",
    paired = TRUE,
    hide.ns = TRUE,
    label = "p.signif") +
  scale_fill_manual(values = c("red", "black"))+
  coord_flip()

ggsave("figures/Supplemental_AverageRelativeAbd_Genus.pdf")
  
```

## Alpha diversity

```{r Generate alpha dversity data}

#generate alpha diversity metrics 
alpha <- microbiome::alpha(ps_data, index = "all")

#assign sample names to the new data 
alpha$X.SampleID <- rownames(alpha)

# extract sample data from the phyloseq object
df <- as(sample_data(ps_data), "data.frame")

# Merge Tables
alpha.table <- merge(alpha, df, by = "X.SampleID")

```

```{r diversity afflicted v. normal}

#Shannon diversity
 ggplot(alpha.table, aes(x = Area_Cond, y = diversity_shannon, fill = Area_Cond)) +
  geom_boxplot() +
    stat_compare_means(method="wilcox") +
  labs(x = "Skin Site",
       y = "Shannon") +
    theme(axis.line.y = element_blank(),
          axis.ticks.y = element_blank(), 
          legend.title = element_blank())

#Number of OTUs
 ggplot(alpha.table, aes(x = Area_Cond, y = observed, fill = Area_Cond)) +
  geom_boxplot() +
    stat_compare_means() +
  labs(x = "Skin Site",
       y = "Oberserved OTUs") +
    theme(axis.line.y = element_blank(),
          axis.ticks.y = element_blank())
 
 #Calculate average number of OTUs per group
 alpha.table %>% 
   group_by(Area_Cond) %>% 
   summarise(mean(observed))

 
 
```

```{r Shannon v. Age regression}


#Shannon vs Age
ggplot(alpha.table,
       aes(x = Age, y = diversity_shannon, fill = Area_Cond, color = Area_Cond)) +
    geom_point(aes(color = Area_Cond)) +
    geom_smooth(method = "lm", fill = "gray", guide = "none") +
    stat_cor() +
    labs(x = "Age", y = "Shannon Diversity", title = "A") +
    scale_color_manual(values = c("red", "black"))+
    guides(color = guide_legend(override.aes = list(shape = 16, size = 3, fill = NA)))+
    theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12), 
        legend.text = element_text(size = 10), 
        legend.title = element_blank())

  

ggsave("figures/Fig1a.pdf", height = 4, width = 5)


```

```{r ages by 20 years}

alpha.table %>% 
  mutate(Age_Cat2 = case_when(Age < 40 ~ "1) Less than 40", 
                              Age < 60 & Age > 39  ~ "2) 40 to 59", 
                              Age > 59 ~ "3) 60+")) %>% 
  ggplot(aes(x = Area_Cond, y = diversity_shannon)) +
  geom_boxplot(aes(color = Area_Cond), show.legend = F) +
  geom_point(aes(color = Area_Cond))+
  stat_compare_means(method="wilcox") +
  stat_cor()+
  scale_color_manual(values = c("red", "black"))+
  facet_wrap(~Age_Cat2)+
  guides(color = guide_legend(override.aes = list(shape = 16, size = 3, fill = NA)))+
  labs(x = " ", y = "Shannon Diversity", title = "B") +
      theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.position = "none")
 
#ggsave("figures/Fig1b.pdf", height = 4, width = 5)


```
```{r figure based on the median age }

alpha.table %>% 
  mutate(Age_Cat2 =if_else(
      Age < median(Age, na.rm = TRUE),
       "Age < 52",  " Age ≥  52")) %>% 
  ggplot(aes(x = Area_Cond, y = diversity_shannon)) +
  geom_boxplot(aes(color = Area_Cond), show.legend = F) +
  geom_point(aes(color = Area_Cond))+
  stat_compare_means(method="wilcox") +
  stat_cor()+
  scale_color_manual(values = c("red", "black"))+
  facet_wrap(~Age_Cat2)+
  guides(color = guide_legend(override.aes = list(shape = 16, size = 3, fill = NA)))+
  labs(x = " ", y = "Shannon Diversity", title = "B") +
      theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        legend.position = "none")

ggsave("figures/fig1brevised.pdf")

```



```{r diversity v. other co-variates}

alpha.table %>% 
  filter(Area_Cond == "Afflicted") %>% 
  ggplot(aes(x = Cleansing_Freq, y = diversity_shannon, fill = Cleansing_Freq)) +
  geom_boxplot() +
    stat_compare_means(label = "p.signif") +
  geom_point()+
  labs(x = " ",
       y = "Shannon Diversity") +
      theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.text.x = element_text(family = "Arial", size = 12),
        axis.text.y = element_text(family = "Arial", size = 12), 
        legend.text = element_text(family = "Arial", size = 10))

alpha.table %>% 
  filter(Area_Cond == "Afflicted") %>%
  mutate(Type = ifelse(Hair_Type == "Natural", "Natural",  "Other")) %>%
  filter(Type != is.na(Type)) %>% 
  ggplot(aes(x = Type, y = diversity_shannon, fill = Type)) +
  geom_boxplot() +
    stat_compare_means(label = "p.signif") +
  geom_point()+
  labs(x = " ",
       y = "Shannon Diversity") +
      theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.text.x = element_text(family = "Arial", size = 12),
        axis.text.y = element_text(family = "Arial", size = 12), 
        legend.text = element_text(family = "Arial", size = 10))

alpha.table %>% 
  filter(Area_Cond == "Afflicted") %>% 
  ggplot(aes(x = Hair_Type, y = diversity_shannon, fill = Hair_Type)) +
  geom_boxplot() +
    stat_compare_means(label = "p.signif") +
  geom_point()+
  labs(x = " ",
       y = "Shannon Diversity") +
      theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.text.x = element_text(family = "Arial", size = 12),
        axis.text.y = element_text(family = "Arial", size = 12), 
        legend.text = element_text(family = "Arial", size = 10))


alpha.table %>% 
  filter(Area_Cond == "Afflicted") %>% 
  ggplot(aes(x = Gender, y = diversity_shannon, fill = Gender)) +
  geom_boxplot() +
    stat_compare_means(label = "p.signif") +
  geom_point()+
  labs(x = " ",
       y = "Shannon Diversity") +
      theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.text.x = element_text(family = "Arial", size = 12),
        axis.text.y = element_text(family = "Arial", size = 12), 
        legend.text = element_text(family = "Arial", size = 10))





```

## Beta Diversity

```{r transform data}

#CLR before Euclidean distance for Aitchison distances
#Center log ratio the phyloseq file
alo_clr <- microbiome::transform(ps_data, "clr")




```

```{r  RDA}

#PCA via phyloseq
ord_clr <- phyloseq::ordinate(alo_clr, "RDA") 

#ord_clr <- phyloseq::ordinate(alo_clr, "PCoA") 

plot_ordination(alo_clr, ord_clr, color = "Area_Cond")

#Plot scree plot
phyloseq::plot_scree(ord_clr) +
  geom_bar(stat="identity", fill = "blue") +
  labs(x = "Axis", y = "Proportion of Variance")

#Examine eigenvalues and % proportion of variance explained
head(ord_clr$CA$eig)

#What proportion of variance explained in actual understandable form as a decimal
sapply(ord_clr$CA$eig[1:10], function(x) x / sum(ord_clr$CA$eig))


```

```{r fig1c}


clr1 <- ord_clr$CA$eig[1] / sum(ord_clr$CA$eig)
clr2 <- ord_clr$CA$eig[2] / sum(ord_clr$CA$eig)


phyloseq::plot_ordination(ps_data, ord_clr, type="samples", color="Area_Cond")+
  geom_point() +
  coord_fixed(clr2 / clr1) +
  stat_ellipse(aes(group = Area_Cond), linetype = 2)+
  scale_color_manual(values = c("red", "black"))+
  theme(legend.title = element_blank(), legend.position = "none")+
  labs(title = "C")


ggsave("figures/Fig1c.pdf", width = 4, height = 6)




```


```{r connect by person ID}

ord <- ordinate(alo_clr, method = "PCoA", distance = "euclidean")

# Extract ordination coordinates and merge with metadata
ord_df <- plot_ordination(alo_clr, ord, type = "samples", justDF = TRUE)

# Add metadata: Site condition and Person_ID
ord_df$Area_Cond <- sample_data(alo_clr)$Area_Cond
ord_df$Person_ID <- sample_data(alo_clr)$Person_ID

# Plot with lines connecting samples from the same individual
ggplot(ord_df, aes(x = Axis.1, y = Axis.2, color = Area_Cond)) +
  geom_point(size = 3) +
  geom_line(aes(group = Person_ID), color = "gray70", linewidth = 0.5) +
  theme_minimal() +
  labs(title = "PCoA (CLR + Euclidean): Afflicted vs. Normal Sites",
       x = "PCoA Axis 1", y = "PCoA Axis 2",
       color = "Site Type") +
  theme(legend.position = "right")

```


```{r ADONIS convariates}

#Generate distance matrix
clr_dist_matrix <- phyloseq::distance(alo_clr, method = "euclidean")

#ADONIS test for Age -> Also significant!
vegan::adonis2(clr_dist_matrix ~phyloseq::sample_data(alo_clr)$Age_Cat2, permutations = 10000)

#ADONIS test for Gender -> Also significant!
vegan::adonis2(clr_dist_matrix ~phyloseq::sample_data(alo_clr)$Gender, permutations = 10000)


```
```{r ANDONIS area condition}

#ADONIS test for Normal vs Afflicted
vegan::adonis2(clr_dist_matrix ~phyloseq::sample_data(alo_clr)$Area_Cond, permutations = 10000, strata=sample_df$Person_ID)

#ADONIS test for Normal vs Afflicted -> Significant
vegan::adonis2(clr_dist_matrix ~phyloseq::sample_data(alo_clr)$Area_Cond, permutations = 10000)

```

```{r Dispersion test}

#Dispersion test for Area_Cond (Normal vs Afflicted)
dispr <- vegan::betadisper(clr_dist_matrix, phyloseq::sample_data(alo_clr)$Area_Cond)
anova(dispr)

#Dispersion test for age
dispr2 <- vegan::betadisper(clr_dist_matrix, phyloseq::sample_data(alo_clr)$Age_Cat2)
anova(dispr2)


#Dispersion test for Gender
dispr3 <- vegan::betadisper(clr_dist_matrix, phyloseq::sample_data(alo_clr)$Gender)
anova(dispr3)



```

```{r Dispersion plots}

#Dispersion plot for Area_Cond + boxplot
plot(dispr, main = "Ordination Centroids and Dispersion Labeled: Aitchison Distance", sub = "")

boxplot(dispr, main = "", xlab = "")

#Dispersion plot for Age_Cat + boxplot
plot(dispr2, main = "Ordination Centroids and Dispersion Labeled:Aitchison Distance", sub = "")

boxplot(dispr2, main = "", xlab = "")


#Dispersion plot for Gender + boxplot
plot(dispr3, main = "Ordination Centroids and Dispersion Labeled:Aitchison Distance", sub = "")
boxplot(dispr3, main = "", xlab = "")

```

```{r Sample Variance}

#Generate distance matrix
clr_dist_matrix <- phyloseq::distance(alo_clr, method = "euclidean")

# Distance matrix to long format
dist_long <- as.data.frame(as.table(as.matrix(clr_dist_matrix)))
colnames(dist_long) <- c("Sample1", "Sample2", "Distance")

#  Add metadata
meta <- sample_df[, c("X.SampleID", "Person_ID", "Area_Cond")]

dist_long <- dist_long %>%
  inner_join(meta, by = c("Sample1" = "X.SampleID")) %>%
  inner_join(meta, by = c("Sample2" = "X.SampleID"),
             suffix = c("_1", "_2"))

#keep a copy of the matrix 
dist_long_1 <- dist_long

# Remove redundant/self comparisons
dist_long <- dist_long %>%
  filter(Sample1 < Sample2)

# Define "Within" vs "Between"
dist_long <- dist_long %>%
  mutate(Comparison = if_else(Person_ID_1 == Person_ID_2, "Within", "Between")) %>% 
  mutate(Condition = Area_Cond_1)

#keep a copy 
dist_long_2 <-dist_long


ggplot(dist_long, aes(x = Comparison, y = Distance, fill = Condition)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) +
  #facet_wrap(~ Condition) +
  labs(title = "Within vs Between-Person Distances by Condition",
       y = "Distance", x = NULL) +
  theme_minimal() +
  scale_fill_manual(values = c("black", "red"))+
  stat_compare_means(method = "wilcox")+
  theme(legend.title = element_blank())

ggsave("figures/varianceWcondition.pdf")


ggplot(dist_long, aes(x = Comparison, y = Distance)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) +
  #facet_wrap(~ Condition) +
  labs(title = "Within vs Between-Person Distances",
       y = "Distance", x = NULL) +
  theme_minimal() +
  stat_compare_means(method = "wilcox")

ggsave("figures/variance.pdf")

```


## Dysbiosis Scores

```{r dysbiosis score}

#center log ratio (clr) transformation
clr <- microbiome::transform(ps_data, "clr")

#make a distance matrix
dist.matrix <- phyloseq::distance(clr, "euclidean") #euclidean distances of clr transformed data are Aitchison distances

#set Normal as the baseline
ref.samples <- sample_names(subset_samples(ps_data, 
                                           Area_Cond == "Normal")) 


#calculate dysbiosis scores
dysbiosis <- euclideanDistCentroids(ps_data,
                                      dist_mat = dist.matrix,
                                      use_squared = F,
                                      group_col = "Area_Cond",
                                      control_label = "Normal",
                                      case_label = "Afflicted")


# order the data 
dysbiosis$Area_Cond <- factor(dysbiosis$Area_Cond, 
                              levels = c("Normal", "Afflicted"))




```

```{r model performance}

#AOC plot to check sensitivity and specificity of the model
AUCplot <- pROC::roc(as.factor(dysbiosis$Area_Cond),
                   dysbiosis$CentroidDist_score,
                   #direction= ">",
                   plot=TRUE,
                   ci = TRUE,
                   auc.polygon=TRUE,
                   max.auc.polygon=TRUE,
                   print.auc=TRUE)

#calculate average dysbiosis score by group
dysbiosis %>% 
  group_by(Area_Cond) %>% 
  summarise(mean(CentroidDist_score))


#check to see if there is a signicant different in dysbiosis scores between groups 
ggplot(dysbiosis, aes(Area_Cond, CentroidDist_score)) +
  geom_boxplot()+
  geom_point()+
  stat_compare_means(method = "wilcox.test")+
  theme_bw()

#set a dysbiosis threshold
dysbiosis <- dysbiosis %>% 
  mutate(dysbiotic = case_when(CentroidDist_score > 0 ~ "Dysbiotic", 
                              CentroidDist_score < 0 ~ "Normobiosis" )) 


#check which hair sites got dysbiosis assignments
dysbiosis %>% 
  group_by(dysbiotic, Area_Cond) %>% 
  count(dysbiotic) %>% 
  arrange(desc(n))




```

```{r Fig 2 Gradient plot}


plotDysbiosisGradient(df=dysbiosis,
                                  score="CentroidDist_score",
                                  high_line = 0.0,
                                  group_var = "Area_Cond",
                                  group_colors=c("Normal" = "black", 
                                                 "Afflicted"= "brown3"),
                                
                        
                                  bg_colors = rev(brewer.pal(9, "Reds")),
                                  jitter_width = 0.1) +
  labs(y="Dysbiosis Score", subtitle = " ") +
  theme(legend.title = element_blank())+
  # adjust the x and y values to fit to plot
  ggplot2::annotate("text",  x = 0.65, y = .1, label = "Center",color="white")

ggsave("Figures/Fig2.pdf", height =6, width =5)

plotDysbiosisGradient(df = dysbiosis,
                      score = "CentroidDist_score",
                      high_line = 0.0,
                      group_var = "Area_Cond",
                      group_colors = c("Normal" = "black", "Afflicted" = "brown3"),
                      bg_colors = rev(brewer.pal(9, "Reds")),
                      jitter_width = 0) +
  geom_text(data = dysbiosis,
            aes(y = CentroidDist_score, 
                x = 1, # or adjust to match the y-location of points
                label = Person_ID),
            #position = position_jitter(width = 0.1, height = 0),
            size = 3, 
            vjust = -1, 
            check_overlap = TRUE) +
  labs(y = "Dysbiosis Score", subtitle = " ") +
  theme(legend.title = element_blank()) +
  annotate("text", x = 0.65, y = 0.1, label = "Center", color = "white")

#ggsave("figures/labeleddysbiois.pdf")


```


## Mixed Effects Model 

```{r prepdata}

ps_data@sam_data$Area_Cond <- as.factor(ps_data@sam_data$Area_Cond)

ps_data@sam_data$Area_Cond <- relevel(ps_data@sam_data$Area_Cond, ref = "Normal")

levels(ps_data@sam_data$Area_Cond)

```

```{r make a count matrix, results = "hide"}

# Aggregate Table by OTU
df.agg <- stats::aggregate(Abundance ~ OTU + X.SampleID, ps_data.df, FUN = sum)

# Make Blank Cells Unspecified
df.agg$OTU[df.agg$OTU == ""] <- "Unassigned"

# Manipulate Data Table to Short Version
df.agg.otus <- as.data.frame(reshape::cast(df.agg, X.SampleID ~ OTU, sum))

data <- df.agg.otus #preserve data before making a matrix

# Make SampleID Rownames and Remove Column
rownames(df.agg.otus) <- df.agg.otus$X.SampleID
df.agg.otus$X.SampleID <- NULL # to make a matrix

# Check Dimensions
dim(df.agg.otus)

```

```{r prepare variables for model}

### Create Variables for Model ###
# Sample Data
df.meta <- sample_data(ps_data)

Age <- df.meta$Age

Area_Cond <- df.meta$Area_Cond

# create data frame containing all the variables of interest
df.meta <- as_data_frame(df.meta)

df.meta.var <- df.meta %>%  dplyr::select(X.SampleID, Person_ID, Age, Age_Cat, Gender)

data.var <- left_join(data, df.meta, by = "X.SampleID" )



```

```{r run model}

#mem <- NBZIMM::mms(y = df.agg.otus, fixed = ~ Area_Cond, data = data.var,  random = ~ 1 | Age,  min.p = 0.2, method = "nb")

#saveRDS(mem,  "output/mem")

```

```{r extract model data}

mem <- readRDS("output/mem")

# Extract data

out <- mem$call$fixed

out = NBZIMM::fixed(mem)$dist
out = out[out[,2]!="(Intercept)", ]
res = out[, 3:5]

#remove the Area_CondAfflicted from the rowname
rownames(res) <- gsub("--Area_CondAfflicted", "", rownames(res)) 

# make a data frame
res.data <- as.data.frame(res)

#add OTU column to the data frame
res.data$OTU <- rownames(res.data)

#filter sigificant results
res.data <- res.data %>% 
  filter(pvalue <0.05)

#join results with all data
res.data.df <- left_join(res.data, ps_data.df, by = "OTU")

#clean up genus column
res.data.df$Genus <- sub("g__", "", res.data.df$Genus)

#number of OTUs that were more abundant in afflicted sites 
res.data %>% filter(Estimate > 0)

#number of unique genera that were differentially abundant
unique(res.data.df$Genus)

#count the Genus assignments of those OTUs
res.data.df %>% 
  distinct(OTU, .keep_all=TRUE) %>% 
  filter(Genus != is.na(Genus)) %>% 
  filter(Genus != "") %>% 
  group_by(Genus) %>% 
  count() %>% 
  arrange(desc(n))





```

```{r Make a nicer plot}

res.data.df %>% 
  filter(pvalue < 0.05) %>% 
  filter(Genus != "Unassigned") %>% 
  filter(Genus != "") %>% 
  mutate(Genus1 = reorder(Genus, Estimate)) %>% 
  ggplot(aes(x = Genus1, y = Estimate)) +
    geom_point(alpha = 0.5) +
    geom_errorbar(aes(ymin=Estimate-Std.Error, ymax=Estimate+Std.Error), width=.1, alpha = 0.5) +
    coord_flip() +
   labs(y = "Estimate", x = " ")+
    geom_hline(yintercept = 0, lty = 2) +
    theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
       axis.text.y = element_text(size = 12)) 
 
ggsave("figures/Fig4.pdf")

```

```{r keep only the OTUs with assigned species}


res.data.df %>% 
  filter(pvalue <0.05) %>% 
  filter(Species != "Unassigned") %>% #remove any OTUs that don't have assigned species
   filter(Species != "s__") %>% 
  mutate(Species1 = reorder(Species, Estimate)) %>% 
  ggplot(aes(x = Species1, y = Estimate, color = Genus)) +
    geom_point(alpha = 0.5)+
    #geom_jitter()+
    geom_errorbar(aes(ymin=Estimate-Std.Error,
                      ymax=Estimate+Std.Error), width=.1, alpha = 0.5) +
    coord_flip() +
    geom_hline(yintercept = 0, lty = 2) +
    theme(axis.line.y = element_blank(),
        axis.ticks.y = element_blank(), 
       axis.title.y= element_blank(),
        axis.text.x = element_text(family = "Arial", size = 10),
        axis.text.y = element_text(family = "Arial", size = 10))



```


## Random Forest with dysbiosis score

```{r set up for RF }

#set dysbiosis threshold and add column 
dysbiosis <- dysbiosis %>% 
  mutate(dysbiotic = case_when(CentroidDist_score > 0 ~ "Dysbiotic", 
                              CentroidDist_score < 0 ~ "Normobiosis" )) 

#add dysbiosis score and assignments to the sample data
ps_data@sam_data$score <- dysbiosis$dysbiotic

ps_data@sam_data$numericScore <- dysbiosis$CentroidDist_score

#Prep data
predict <- t(otu_table(ps_data))

#Check dimensions
dim(predict)

#Create response variable
res <- as.factor(sample_data(ps_data)$score)

#Combine predict variable and response variable into one dataframe
machine.data <- data.frame(res, predict)

#check dimensions
dim(machine.data)

```

```{r class RF}

# 
#class <- randomForest(res ~ ., data = machine.data, ntree = 1001, importance = TRUE, nodesize = 1)

#saveRDS(class, "output/RF") 

class <- readRDS("output/RF") #by default a random forest will be different every time you run it, so here we're loading saved RF previously made

print(class)


```

```{r Confusion Matrix Plot for RF}

confusiondf <- as.data.frame(class$confusion)

confusionfixed <- data.frame(Actual = c("Dysbiotic", "Dysbiotic", "Normobiosis", "Normobiosis"), Predicted = c("Dysbiotic", "Normobiosis", "Dysbiotic", "Normobiosis"), Count = c(confusiondf[1,1], confusiondf[1,2], confusiondf[2,1], confusiondf[2,2]), Freq = c(confusiondf[1,3], confusiondf[1,3], confusiondf[2,3], confusiondf[2,3]))

ggplot(confusionfixed, aes(x = Predicted, y = Actual, fill = Count)) +
  geom_tile()+
  geom_text(aes(label = Count), fontface="bold", color = "white") +
  geom_text(aes(label = Freq, vjust = 3), fontface="bold") +
  theme_bw() +
  theme(legend.position="none") +
  labs(x = "Predicted", y = "Actual")

```

```{r RF important taxa }

#extract the predictors from the RF 
imp.taxa <- randomForest::importance(class)

#make a dataframe 
imp.taxa <- data.frame(predictors = rownames(imp.taxa), imp.taxa)

#rename the object for easier coding
imp <- imp.taxa

# Order the predictor levels by importance (Mean decrease accuracy)
imp.sort <- arrange(imp, desc(MeanDecreaseAccuracy))
imp.sort$predictors <- factor(imp.sort$predictors, levels = imp.sort$predictors)

# Select the top 100 predictors
imp.100 <- imp.sort[1:100, ]

# Change Column name to say "OTUID" rather than "predictors"
colnames(imp.100)[which(names(imp.100) == "predictors")] <- "OTUID"

# Remove "X" from OTUID column
imp.100$OTUID <- gsub("X", "", paste(imp.100$OTUID))

# Make Taxa table from phyloseq object a data frame
otu_df <- as.data.frame(tax_table(ps_data))

# Make OTU IDs (row names) into column
otu_df$OTUID <- rownames(otu_df)

# Merge two data frames using matched column so that we know which taxa are assigned to the OTUs
imp100.merged <- merge(imp.100, otu_df, by = "OTUID")

#rename the object
RFtop100_Otus <- imp100.merged


#count the number of unique genera
unique(RFtop100_Otus$Genus)



```

```{r Mean Decrease Accuracy plots for classification RF }

#cleanup Genus names
imp100.merged$Genus <- sub("g__", "", imp100.merged$Genus)

#plot 
imp100.merged %>% 
  mutate(Genus = reorder(Genus, MeanDecreaseAccuracy)) %>% 
  filter(Genus != "") %>% 
  filter(Genus != is.na(Genus)) %>% 
   ggplot(aes(x = reorder(Genus, MeanDecreaseAccuracy, sum), 
             y = MeanDecreaseAccuracy, 
             fill = OTUID)) +  # Stacked by OTU
  geom_bar(stat = "identity", color = "black") +
  coord_flip() +
  labs(x = "Top taxa for classifying dysbiotic scalp sites",  y = "Mean Decrease Accuracy (%)")+
  theme(legend.position = "none")

ggsave("figures/Fig3.pdf", height = 5, width =6)




```

## Compare Important Taxa 


```{r v2 Extract the significant taxa from both tests}

#extract diff abundant taxa from the mixed effected model
res.data <- res.data %>% filter(pvalue <0.05)

#check the intersection of OTUs between the random forest and mixed effects models
shared_sig.OTU <- intersect(res.data$OTU, RFtop100_Otus$OTU)

shared_sig.OTU #42 shared otus 

#make a new data frame keeping only OTUs sig in both models
OTU.filt.df <- ps_data.df %>% filter(OTU %in% shared_sig.OTU) 

#repeat for the relative abundance data frame 
OTU.filt_rel.df <- ps_rel.df%>% filter(OTU %in% shared_sig.OTU)



```

```{r Venn Diagram}


#add a variable to each set of results indicating which test they came from 

res.data$test <- "Mixed Effects Model" 

RFtop100_Otus$test <- "Random Forest Classifer"

#change the column name so they match
RFtop100_Otus$OTU <- RFtop100_Otus$OTUID

#create a shared data frame
shared <- full_join(res.data, RFtop100_Otus, by = c("OTU", "test"))

#keep only OTUs that are in both models
keep <- union(res.data$OTU, RFtop100_Otus$OTU)
shared <- shared %>%  filter(OTU %in% keep)

#make a list with the two tests seperated
data_list <- split(shared$OTU, shared$test)

#make a venn diagram
ggvenn(data_list, label_sep = "\n", fill_color = c("white", "white"), show_elements = F)




```




## Confirm differentially abundant OTUs

```{r remove OTUs that are not sig different}

#transform to log10 abundances
OTU.filt.df$log10Abund <- log10( 1 + OTU.filt.df$Abundance)

# Run Wilcoxon test for each OTU and store p-values
otu_pvals_notsig <- OTU.filt.df %>%
  group_by(OTU) %>%
  summarise(p_value = wilcox.test(log10Abund ~ Area_Cond)$p.value) %>% 
  filter(p_value > 0.05)

#Extract OTU names from the data frame of shared OTUs by both RF and Mixed effects model 
OTUs <- sort(unique(OTU.filt.df$OTU))

#OTUs to remove
remove <- otu_pvals_notsig$OTU

#Significant OTUs
OTUs_sig <- OTUs[!OTUs %in% remove]

#keep only significant OTUs
OTU.filt.df <- OTU.filt.df %>% 
  filter(OTU %in% OTUs_sig)

OTU.filt_rel.df <- OTU.filt_rel.df%>% 
  filter(OTU %in% OTUs_sig)

sort(unique(OTU.filt_rel.df$Genus))

sort(unique(OTU.filt.df$Genus))


```



```{r Core taxa plot abundance of genera from the filtered OTUs}


OTU.filt_rel.df %>% 
  filter(Genus != "") %>%
  group_by(Genus) %>%  # Group by Genus before reordering
  mutate(OTU = factor(OTU, levels = unique(OTU[order(Abundance, decreasing = TRUE)]))) %>% 
  ggplot(aes(OTU, Abundance, fill = Area_Cond)) +
  geom_boxplot(alpha =0.7, outliers = F) +
  geom_point(aes(OTU, Abundance), position = position_dodge(width = 0.75), size = 0.3, alpha = 0.7) +
  scale_y_log10(breaks = scales::breaks_log(n = 10),     
                labels = scales::number_format(accuracy = 0.0001)) +
  coord_flip() +
  labs(y= "Relative Abundance") +
  scale_fill_manual(values = c("red", "black")) +
  theme(legend.title = element_blank(),
  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 0.5), 
  axis.text.y = element_blank())+
  facet_wrap(~Genus, ncol = 3, scales = "free_y") 

ggsave("figures/Figure5.pdf")


 


```



